"""Phase 2.0 Open-World Discovery：候选发现/分类/清洗/验证/升格模块包。

从现有 KB 中发现 ontology 外的新知识结构，候选经验证后安全升格为新节点。
Pipeline（用户定 2026-08-26）：
    Candidate Scanner → Candidate Typing → Alias/Existing Filter → Candidate Pool
      → Targeted Verification Search → Evidence Aggregation → Promotion Decision
      → Ontology Expansion
"""

from .candidate import (
    DiscoveryCandidate,
    RawCandidate,
    InvalidTransition,
    CANDIDATE_TYPES,
    CANDIDATE_SOURCES,
    STATUS_FLOW,
    PROMOTION_RULES,
    STATUS_LABELS,
    can_verify,
    verification_priority,
    can_promote,
    merge_pool,
    get_tracking,
    evidence_signature,
)
from .scanner import scan_kb
from .typer import type_candidate, domain_relevance_level
from .canonical_filter import canonical_match, existing_knowledge_match
from .promoter import (
    PromotionProposal,
    PromotionRelation,
    PROMOTION_ACTIONS,
    PROPOSAL_STATUS,
    TYPE_TO_ACTION,
    decide_action,
    build_proposal,
)
from .round_state import (
    DiscoveryRound,
    file_sha256,
    kb_version,
    ontology_version,
    load_rounds,
    save_rounds,
    append_round,
    latest_round,
)
from .prioritizer import (
    DEFAULT_WEIGHTS,
    DEFAULT_MAX_PER_TYPE,
    TYPE_TO_STRUCTURAL_SCORE,
    novelty_score,
    relevance_score,
    evidence_score,
    structural_score,
    cost_score,
    score_candidate,
    score_with_penalty,
    no_evidence_gain_streak,
    eligible,
    select,
    update_tracking_after_verify,
)
from .metrics import (
    compute_round_metrics,
    count_new_nodes_by_type,
    format_round_report,
)
from .stopping import should_stop, stop_reason_label
from .approval_queue import (
    load_queue, save_queue, add_proposal, has_proposal,
    list_queue, approve_item, reject_item,
    proposal_ids_created, proposal_ids_approved,
)
from .controller import DiscoveryController, VerifierUnavailableError
from .query_registry import (
    QueryRecord, normalize_query, load_registry, save_registry,
    register, has_executed, mark_executed,
)
from .expander import generate_queries, count_by_family
from .paper_provenance import (
    DiscoveryPaperProvenance, load_provenance, save_provenance,
    add_provenance, papers_by_query, queries_for_paper, paper_ids,
)
from .discovery_retriever import (
    QueryExecution, execute_query, execute_pending, build_existing_universe,
    load_staging, save_staging, add_staging_paper, summarize,
)
from .staging_pipeline import (
    query_core_terms, screen_relevance, screen_staging, extract_candidates,
    edges_to_discovery_layer, save_discovery_edges, load_discovery_edges,
    DiscoveryLayerView, candidate_diff, rerun_scanner, build_trace, METRIC_KEYS,
    assert_all_screened, canonical_identity, canonical_candidates,
    audit_new_candidates,
)
from .trajectory import (
    DiscoveryTrajectory, load_trajectories, save_trajectories, upsert_trajectory,
    outcome_from_query, record_from_query, update_downstream, analyze_trajectories,
)
from .query_registry import _query_id

__all__ = [
    "DiscoveryCandidate",
    "RawCandidate",
    "InvalidTransition",
    "CANDIDATE_TYPES",
    "CANDIDATE_SOURCES",
    "STATUS_FLOW",
    "PROMOTION_RULES",
    "STATUS_LABELS",
    "can_verify",
    "verification_priority",
    "can_promote",
    "merge_pool",
    "get_tracking",
    "evidence_signature",
    "scan_kb",
    "type_candidate",
    "domain_relevance_level",
    "canonical_match",
    "existing_knowledge_match",
    "PromotionProposal",
    "PromotionRelation",
    "PROMOTION_ACTIONS",
    "PROPOSAL_STATUS",
    "TYPE_TO_ACTION",
    "decide_action",
    "build_proposal",
    "DiscoveryRound",
    "file_sha256",
    "kb_version",
    "ontology_version",
    "load_rounds",
    "save_rounds",
    "append_round",
    "latest_round",
    "DEFAULT_WEIGHTS",
    "DEFAULT_MAX_PER_TYPE",
    "TYPE_TO_STRUCTURAL_SCORE",
    "novelty_score",
    "relevance_score",
    "evidence_score",
    "structural_score",
    "cost_score",
    "score_candidate",
    "score_with_penalty",
    "no_evidence_gain_streak",
    "eligible",
    "select",
    "update_tracking_after_verify",
    "compute_round_metrics",
    "count_new_nodes_by_type",
    "format_round_report",
    "should_stop",
    "stop_reason_label",
    "load_queue",
    "save_queue",
    "add_proposal",
    "has_proposal",
    "list_queue",
    "approve_item",
    "reject_item",
    "proposal_ids_created",
    "proposal_ids_approved",
    "DiscoveryController",
    "VerifierUnavailableError",
    "QueryRecord",
    "normalize_query",
    "load_registry",
    "save_registry",
    "register",
    "has_executed",
    "mark_executed",
    "generate_queries",
    "count_by_family",
    "DiscoveryPaperProvenance",
    "load_provenance",
    "save_provenance",
    "add_provenance",
    "papers_by_query",
    "queries_for_paper",
    "paper_ids",
    "QueryExecution",
    "execute_query",
    "execute_pending",
    "build_existing_universe",
    "load_staging",
    "save_staging",
    "add_staging_paper",
    "summarize",
    "query_core_terms",
    "screen_relevance",
    "screen_staging",
    "extract_candidates",
    "edges_to_discovery_layer",
    "save_discovery_edges",
    "load_discovery_edges",
    "DiscoveryLayerView",
    "candidate_diff",
    "rerun_scanner",
    "build_trace",
    "METRIC_KEYS",
    "assert_all_screened",
    "canonical_identity",
    "canonical_candidates",
    "audit_new_candidates",
    "_query_id",
    "DiscoveryTrajectory",
    "load_trajectories",
    "save_trajectories",
    "upsert_trajectory",
    "outcome_from_query",
    "record_from_query",
    "update_downstream",
    "analyze_trajectories",
]
